---
- name: A demo playbook
  hosts: 10.4.6.10
  connection: local

  environment:
#    F5_SERVER: "{{ ansible_host }}"
     F5_SERVER: 10.4.6.10 
 #   F5_USER: "{{ username }}"
     F5_USER: admin
 #   F5_PASSWORD: "{{ password }}"
     F5_PASSWORD: bigip123 
 #   F5_SERVER_PORT: "{{ server_port }}"
     F5_SERVER_PORT: 443 
 #   F5_VALIDATE_CERTS: "{{ validate_certs }}"
     F5_VALIDATE_CERTS: no

  tasks:
#    - name: Provision ASM
#      bigip_provision:
#        module: asm

    - name: Create ASM policy, compact XML file
      bigip_asm_policy:
        name: my-asm-policy1
    #    file: files/actors.xml
#        state: present
        template: SharePoint 2007 (http)
      delegate_to: localhost
